### ISSUE TITLE
Introduce Seed to Make Simulation Reproducible

### ISSUE THREAD

**Issue by ksolarski** [RyanAugust/PySiMMMulator#18]
**Is your feature request related to a problem? Please describe.**
Currently I see not way to make my simulation reproducible (please correct me if I'm wrong). If somebody discovers some issue with the package, it's easier to debug if one is able to fully reproduce the simulation.

**Describe the solution you'd like**
Add an optional seed using `np.random.seed()` function.

**Comment by RyanAugust** [comment]
PR #20 is merged and uses the more modern [np.random.Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator) as opposed to the `np.random.seed` call with hits the global `RandomState`.
Good idea on the added coverage this provides for reproducibility.
